export const movieData = {
  lotr: [
    {
      "_id": "5cd95395de30eff6ebccde5c",
      "name": "The Fellowship of the Ring",
      "series": "The Lord of the Rings",
      "runtimeInMinutes": 178,
      "budgetInMillions": 93,
      "boxOfficeRevenueInMillions": 871.5,
      "academyAwardNominations": 13,
      "academyAwardWins": 4,
      "rottenTomatoesScore": 91,
      "imdbScore": 8.9,
      "tmdbScore": 84,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt0120737/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_fellowship_of_the_ring",
      "tmdbUrl": "https://www.themoviedb.org/movie/120-the-lord-of-the-rings-the-fellowship-of-the-ring?language=en-US",
      "oneLine": "One ring to rule them all.",
      "summary": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",

    },
    {
      "_id": "5cd95395de30eff6ebccde5b",
      "name": "The Two Towers",
      "series": "The Lord of the Rings",
      "runtimeInMinutes": 179,
      "budgetInMillions": 94,
      "boxOfficeRevenueInMillions": 926,
      "academyAwardNominations": 6,
      "academyAwardWins": 2,
      "rottenTomatoesScore": 96,
      "imdbScore": 8.8,
      "tmdbScore": 84,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt0167261/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_two_towers",
      "tmdbUrl": "https://www.themoviedb.org/movie/121-the-lord-of-the-rings-the-two-towers?language=en-US",
      "oneLine": "The fellowship is broken. The power of darkness grows...",
      "summary": "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
    },
    {
      "_id": "5cd95395de30eff6ebccde5d",
      "name": "The Return of the King",
      "series": "The Lord of the Rings",
      "runtimeInMinutes": 201,
      "budgetInMillions": 94,
      "boxOfficeRevenueInMillions": 1120,
      "academyAwardNominations": 11,
      "academyAwardWins": 11,
      "rottenTomatoesScore": 95,
      "imdbScore": 9.0,
      "tmdbScore": 85,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt0167260/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_lord_of_the_rings_the_return_of_the_king",
      "tmdbUrl": "https://www.themoviedb.org/movie/122-the-lord-of-the-rings-the-return-of-the-king?language=en-US",
      "oneLine": "There can be no triumph without loss. No victory without suffering. No freedom without sacrifice.",
      "summary": "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    }
  ],
  hobbit: [
    {
      "_id": "5cd95395de30eff6ebccde58",
      "name": "The Unexpected Journey",
      "series": "The Hobbit",
      "runtimeInMinutes": 169,
      "budgetInMillions": 200,
      "boxOfficeRevenueInMillions": 1021,
      "academyAwardNominations": 3,
      "academyAwardWins": 1,
      "rottenTomatoesScore": 64,
      "imdbScore": 7.8,
      "tmdbScore": 74,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt0167260/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_hobbit_an_unexpected_journey",
      "tmdbUrl": "https://www.themoviedb.org/movie/49051-the-hobbit-an-unexpected-journey?language=en-US",
      "oneLine": "From the smallest beginnings come the greatest legends.",
      "summary": "Bilbo Baggins, a hobbit enjoying his quiet life, is swept into an epic quest by Gandalf the Grey and thirteen dwarves who seek to reclaim their mountain home from Smaug, the dragon.",
    },
    {
      "_id": "5cd95395de30eff6ebccde59",
      "name": "The Desolation of Smaug",
      "series": "The Hobbit",
      "runtimeInMinutes": 161,
      "budgetInMillions": 217,
      "boxOfficeRevenueInMillions": 958.4,
      "academyAwardNominations": 3,
      "academyAwardWins": 0,
      "rottenTomatoesScore": 75,
      "imdbScore": 7.8,
      "tmdbScore": 76,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/xQYiXsheRCDBA39DOrmaw1aSpbk.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt1170358/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_hobbit_the_desolation_of_smaug",
      "tmdbUrl": "https://www.themoviedb.org/movie/57158-the-hobbit-the-desolation-of-smaug?language=en-US",
      "oneLine": "Beyond darkness... beyond desolation... lies the greatest danger of all.",
      "summary": "The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug.",
    },
    {
      "_id": "5cd95395de30eff6ebccde5a",
      "name": "The Battle of the Five Armies",
      "series": "The Hobbit",
      "runtimeInMinutes": 144,
      "budgetInMillions": 250,
      "boxOfficeRevenueInMillions": 956,
      "academyAwardNominations": 1,
      "academyAwardWins": 0,
      "rottenTomatoesScore": 60,
      "imdbScore": 7.4,
      "tmdbScore": 73,
      "coverUrl": "https://www.themoviedb.org/t/p/w1280/xT98tLqatZPQApyRmlPL12LtiWp.jpg",
      "imdbUrl": "https://www.imdb.com/title/tt2310332/",
      "rtUrl": "https://www.rottentomatoes.com/m/the_hobbit_the_battle_of_the_five_armies",
      "tmdbUrl": "https://www.themoviedb.org/movie/122917-the-hobbit-the-battle-of-the-five-armies?language=en-US",
      "oneLine": "Witness the defining chapter of the Middle-Earth saga",
      "summary": "Following Smaug's attack on Laketown, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
    }
  ]
}